package com.wittyfeed.sdk.onefeed.DataStoreManagement;

import android.support.annotation.Nullable;

import com.wittyfeed.sdk.onefeed.Models.Block;
import com.wittyfeed.sdk.onefeed.Models.MainDatum;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * Stores the Data-Model which is used through the app
 *
 * has 4 data model objects -
 *      1) mainFeedData: the data-model of main Feed
 *      2) searchFeedData: the data-model of feed generated by search
 *      3) searchDefaultData: the data-model which will be visible by default in the search feed
 *      4) interestDataDatum: the data-model of the fetched available interests on server
 *
 * has other helper data variables -
 *      1) mainFeedDataOffset: the offset which is currently active for main OneFeed
 *      2) lastStringSearchedL the last string which was searched in search Feed
 *
 * has several methods that perform the following operations -
 *      1) clear, reset, set, get and append in data of mainFeed
 *      2) clear, reset, set, get and append in data of searchFeed
 *      3) clear, reset, set, get and append in data of searchDefaultFeed
 *      4) clear, reset, set, get and append in data of interestDataDatum
 *      5) reset or increment mainFeed offset
 *      6) reset, set and get the lastStringSearched of searchFeed
 *
 * Read about: DataStoreManager, DataParser, Model Classes
 */

public final class DataStore {

    public MainDatum getMainFeedData() {
        return mainFeedData;
    }

    private MainDatum mainFeedData;
    private MainDatum searchFeedData;
    private MainDatum searchDefaultData;
    private MainDatum interestsDataDatum;

    private int mainFeedDataOffset = 0;
    private String lastStringSearched;


    /**
     * Clears the main Feed array
     */

    public void clearMainFeedDataArray(){
        if(mainFeedData != null) {
            mainFeedData.getBlocks().clear();
        }
    }

    /**
     * Appends tbe data to the main list of Blocks
     */

    public void appendInMainFeedDataArray(MainDatum datumToAppend){
        if(mainFeedData!=null)
            mainFeedData.getBlocks().addAll(datumToAppend.getBlocks());
    }

    /**
     * Returns the main feed data list
     */

    public List<Block> getMainFeedDataBlockArr(){
        return mainFeedData.getBlocks();
    }

    /**
     * Set main feed data
     */
    public void setMainFeedData(MainDatum mainFeedData) {
        this.mainFeedData = mainFeedData;
    }

    /**
     * Increments the main feed offset by 1
     */
    public void incrementMainFeedDataOffset(){
        this.mainFeedDataOffset += 1;
    }

    /**
     * Resets the main feed offset to 0
     */

    public void resetMainFeedDataOffset() {
        this.mainFeedDataOffset = 0;
    }

    /**
     * Returns the main feed data offset
     */

    public int getMainFeedDataOffset() {
        return mainFeedDataOffset;
    }

    /**
     * Returns the user id from Config
     */

    public String getUserIdFromConfig() {
        return mainFeedData.getConfig().getUser_id();
    }


    /**
     * Clears Search Feed Data Array
     */

    public void clearSearchFeedDataArray(){
        if(searchFeedData != null) {
            searchFeedData.getBlocks().clear();
        }
    }

    /**
     * Appends Search Feed Data Array
     */

    public void appendInSearchFeedDataArray(List<Block> blocksToAppend){
        searchFeedData.getBlocks().addAll(blocksToAppend);
    }

    /**
     * Returns Feed data block array
     */

    public List<Block> getSearchFeedDataBlockArr(){
        return searchFeedData.getBlocks();
    }

    /**
     * Sets Search Feed data
     */
    public void setSearchFeedData(MainDatum searchFeedData) {
        MainDatum tempDatum = new MainDatum();
        tempDatum.setConfig(searchFeedData.getConfig());
        tempDatum.setBlocks(new ArrayList<Block>());
        tempDatum.getBlocks().addAll(searchFeedData.getBlocks());
        this.searchFeedData = tempDatum;
    }

    /**
     * Resets the last string searched to empty string
     */

    public void resetLastStringSearched() {
        this.lastStringSearched = "";
    }

    /**
     * Returns the last string searched
     */

    public String getLastStringSearched() {
        return lastStringSearched;
    }

    /**
     * Sets the last string attached
     */
    public void setLastStringSearched(String lastStringSearched) {
        this.lastStringSearched = lastStringSearched;
    }

    /**
     * Clears default search data array
     */
    public void clearSearchDefaultDataArray(){
        if(searchDefaultData != null) {
            searchDefaultData.getBlocks().clear();
        }
    }

    /**
     * Appends the passed data to search default array
     */

    public void appendInSearchDefaultDataArray(MainDatum datumToAppend){
        searchDefaultData.getBlocks().addAll(datumToAppend.getBlocks());
    }

    /**
     * Returns the Search default data block array
     */
    public List<Block> getSearchDefaultDataBlockArr(){
        return searchDefaultData.getBlocks();
    }

    /**
     * Returns default search data array
     */
    public MainDatum getSearchDefaultDatum(){
        return searchDefaultData;
    }

    /**
     * Sets the default search data
     */
    public void setSearchDefaultData(MainDatum searchDefaultData) {
        this.searchDefaultData = searchDefaultData;
    }

    /**
     * Clears the interest data list
     */
    public void clearInterestsDataDatum(){
        if(interestsDataDatum != null) {
            interestsDataDatum.getBlocks().clear();
        }
    }

    /**
     * Appends the passed data to interest data list
     */
    public void appendInInterestsDataArray(MainDatum datumToAppend){
        interestsDataDatum.getBlocks().addAll(datumToAppend.getBlocks());
    }

    /**
     * Returns the interest data block array
     */
    @Nullable
    public List<Block> getInterestsDataBlockArray(){
        if(interestsDataDatum != null) {
            return interestsDataDatum.getBlocks();
        } else {
            return null;
        }
    }

    /**
     * Sets the interest data list
     */
    public void setInterestsDataDatum(MainDatum interestsDataDatum) {
        this.interestsDataDatum = interestsDataDatum;
    }
}
