package com.wittyfeed.sdk.onefeed.DataStoreManagement;

import android.support.annotation.Nullable;
import android.util.Log;

import com.wittyfeed.sdk.onefeed.Models.Block;
import com.wittyfeed.sdk.onefeed.Models.Card;
import com.wittyfeed.sdk.onefeed.Models.MainDatum;
import com.wittyfeed.sdk.onefeed.OneFeedMain;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * Stores the Data-Model which is used through the app
 *
 * has 4 data model objects -
 *      1) mainFeedData: the data-model of main Feed
 *      2) searchFeedData: the data-model of feed generated by search
 *      3) searchDefaultData: the data-model which will be visible by default in the search feed
 *      4) interestDataDatum: the data-model of the fetched available interests on server
 *
 * has other helper data variables -
 *      1) mainFeedDataOffset: the offset which is currently active for main OneFeed
 *      2) lastStringSearchedL the last string which was searched in search Feed
 *
 * has several methods that perform the following operations -
 *      1) clear, reset, set, get and append in data of mainFeed
 *      2) clear, reset, set, get and append in data of searchFeed
 *      3) clear, reset, set, get and append in data of searchDefaultFeed
 *      4) clear, reset, set, get and append in data of interestDataDatum
 *      5) reset or increment mainFeed offset
 *      6) reset, set and get the lastStringSearched of searchFeed
 *
 * Read about: DataStoreManager, DataParser, Model Classes
 */

public final class DataStore {

    public MainDatum getMainFeedData() {
        return mainFeedData;
    }

    private MainDatum mainFeedData;

    public ArrayList<Card> getAllCardData() {
        return allCardData;
    }

    private ArrayList<Card> allCardData = new ArrayList<>();
    private MainDatum searchFeedData;
    private MainDatum searchDefaultData;
    private MainDatum interestsDataDatum;
    private MainDatum nonRepeatingDatum;

    public Block getRepeatingDatum() {
        return repeatingDatum;
    }

    private Block repeatingDatum;

    private int mainFeedDataOffset = 0;
    private String lastStringSearched;
    boolean isDataUpdated = false;



    /**
     * Clears the main Feed array
     */

    public void clearMainFeedDataArray(){
        if(mainFeedData != null) {
            mainFeedData.getBlocks().clear();
        }
    }


    /**
     * Appends tbe data to the main list of Blocks
     */

    public void appendInMainFeedDataArray(MainDatum datumToAppend){
        if(mainFeedData!=null)
            mainFeedData.getBlocks().addAll(datumToAppend.getBlocks());
    }

    public void appendInRepeatingDataArray(Block datumToAppend){
        if(repeatingDatum!=null)
            repeatingDatum.getCards().addAll(datumToAppend.getCards());
    }


    public void appendInAllCardDataArray(MainDatum datumToAppend){
        if(mainFeedData!=null)
            mainFeedData.getBlocks().addAll(datumToAppend.getBlocks());
    }

    /**
     * Returns the main feed data list
     */

    public List<Block> getMainFeedDataBlockArr(){
        return mainFeedData.getBlocks();
    }

    /**
     * Set main feed data
     */
    public void setMainFeedData(MainDatum mainFeedData) {
        this.mainFeedData = mainFeedData;
//        OneFeedMain.getInstance().getInstanceDataStore().getCardArray();
    }

    public void setRepeatingBlock(Block repeatingDatum) {
        this.repeatingDatum = repeatingDatum;
    }

    /**
     * Increments the main feed offset by 1
     */
    public void incrementMainFeedDataOffset(){
        this.mainFeedDataOffset += 1;
    }

    /**
     * Resets the main feed offset to 0
     */

    public void resetMainFeedDataOffset() {
        this.mainFeedDataOffset = 0;
    }

    /**
     * Returns the main feed data offset
     */

    public int getMainFeedDataOffset() {
        return mainFeedDataOffset;
    }

    /**
     * Returns the user id from Config
     */

    public String getUserIdFromConfig() {
        return mainFeedData.getConfig().getUser_id();
    }


    /**
     * Clears Search Feed Data Array
     */

    public void clearSearchFeedDataArray(){
        if(searchFeedData != null) {
            searchFeedData.getBlocks().clear();
        }
    }

    /**
     * Appends Search Feed Data Array
     */

    public void appendInSearchFeedDataArray(List<Block> blocksToAppend){
        searchFeedData.getBlocks().addAll(blocksToAppend);
    }

    /**
     * Returns Feed data block array
     */

    public List<Block> getSearchFeedDataBlockArr(){
        return searchFeedData.getBlocks();
    }

    /**
     * Sets Search Feed data
     */
    public void setSearchFeedData(MainDatum searchFeedData) {
        MainDatum tempDatum = new MainDatum();
        tempDatum.setConfig(searchFeedData.getConfig());
        tempDatum.setBlocks(new ArrayList<Block>());
        tempDatum.getBlocks().addAll(searchFeedData.getBlocks());
        this.searchFeedData = tempDatum;
    }

    /**
     * Resets the last string searched to empty string
     */

    public void resetLastStringSearched() {
        this.lastStringSearched = "";
    }

    /**
     * Returns the last string searched
     */

    public String getLastStringSearched() {
        return lastStringSearched;
    }

    /**
     * Sets the last string attached
     */
    public void setLastStringSearched(String lastStringSearched) {
        this.lastStringSearched = lastStringSearched;
    }

    /**
     * Clears default search data array
     */
    public void clearSearchDefaultDataArray(){
        if(searchDefaultData != null) {
            searchDefaultData.getBlocks().clear();
        }
    }

    /**
     * Appends the passed data to search default array
     */

    public void appendInSearchDefaultDataArray(MainDatum datumToAppend){
        searchDefaultData.getBlocks().addAll(datumToAppend.getBlocks());
    }

    /**
     * Returns the Search default data block array
     */
    public List<Block> getSearchDefaultDataBlockArr(){
        return searchDefaultData.getBlocks();
    }

    /**
     * Returns default search data array
     */
    public MainDatum getSearchDefaultDatum(){
        return searchDefaultData;
    }

    /**
     * Sets the default search data
     */
    public void setSearchDefaultData(MainDatum searchDefaultData) {
        this.searchDefaultData = searchDefaultData;
    }

    public void setNonRepeatingDatum(MainDatum nonRepeatingDatum) {
        this.nonRepeatingDatum = nonRepeatingDatum;
    }

    public MainDatum getNonRepeatingDatum() {
        return nonRepeatingDatum;
    }

    /**
     * Clears the interest data list
     */
    public void clearInterestsDataDatum(){
        if(interestsDataDatum != null) {
            interestsDataDatum.getBlocks().clear();
        }
    }

    /**
     * Appends the passed data to interest data list
     */
    public void appendInInterestsDataArray(MainDatum datumToAppend){
        interestsDataDatum.getBlocks().addAll(datumToAppend.getBlocks());
    }

    /**
     * Returns the interest data block array
     */
    @Nullable
    public List<Block> getInterestsDataBlockArray(){
        if(interestsDataDatum != null) {
            return interestsDataDatum.getBlocks();
        } else {
            return null;
        }
    }

    /**
     * Sets the interest data list
     */
    public void setInterestsDataDatum(MainDatum interestsDataDatum) {
        this.interestsDataDatum = interestsDataDatum;
    }

//    public void refresh_all_card_arr(){
//        allCardData.clear();
//        if (!isDataUpdated) {
//            if(mainFeedData.getBlocks().size() > 0){
//                for (int i = 0; i < mainFeedData.getBlocks().size(); i++) {
//                    ourInstance.block_arr.get(i).setBlock_pos(i);
//                    for (int j = 0; j < ourInstance.block_arr.get(i).getStory().size(); j++) {
//                        if(!ourInstance.block_arr.get(i).getStory().get(j).getCardType().equalsIgnoreCase("filler")){
//                            ourInstance.block_arr.get(i).getStory().get(j).setBlock_pos(i);
//                            ourInstance.block_arr.get(i).getStory().get(j).setStory_pos(j);
//                            ourInstance.block_arr.get(i).getStory().get(j).setAll_card_pos(ourInstance.all_card_arr.size());
//                            ourInstance.all_card_arr.add(ourInstance.block_arr.get(i).getStory().get(j));
//                        }
//                    }
//                }
//            }
//            sort_cards_in_categories();
//        } else {
//
//        }
//    }

    public void buildAllCardArray(){
        if(OneFeedMain.getInstance().getInstanceDataStore().repeatingDatum!=null){
            if(allCardData == null)
                allCardData = new ArrayList<Card>();
            OneFeedMain.getInstance().getInstanceDataStore().getAllCardData().clear();
            allCardData.addAll(repeatingDatum.getCards());
            for(int i = 0; i<repeatingDatum.getCards().size() ; i++)
                Log.i("ALLCARDSTITLE", "getCardArray: "+repeatingDatum.getCards().get(i).getStoryTitle());
        }
    }
}
